const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
API_BASE: process.env.API_BASE || "https://arslan-apis.vercel.app/",
API_KEY: process.env.API_KEY || "arslanmdofficialadmin",
AUTO_STATUS_SEEN: process.env.AUTO_STATUS_SEEN || "true",
AUTO_STATUS_REPLY: process.env.AUTO_STATUS_REPLY || "false",
AUTO_STATUS_REACT: process.env.AUTO_STATUS_REACT || "false",
AUTO_STATUS_MSG: process.env.AUTO_STATUS_MSG || "*SEEN YOUR STATUS BY ABDULLAH-BOTZ 🤍*",
AUTO_BIO: process.env.AUTO_BIO || "true",
GOODBYE: process.env.GOODBYE || "false",
ADMIN_EVENTS: process.env.ADMIN_EVENTS || "false",
PREFIX: process.env.PREFIX || ".",
BOT_NAME: process.env.BOT_NAME || "ABDULLAH-BOTZ",
STICKER_NAME: process.env.STICKER_NAME || "ABDULLAH-BOTZ",
CUSTOM_REACT: process.env.CUSTOM_REACT || "false",
CUSTOM_REACT_EMOJIS: process.env.CUSTOM_REACT_EMOJIS || "💝,💖,💗,❤️‍🩹,❤️,🧡,💛,💚,💙,💜,🤎,🖤,🤍",
DELETE_LINKS: process.env.DELETE_LINKS || "false",
OWNER_NUMBER: process.env.OWNER_NUMBER || "923044975027",
OWNER_NAME: process.env.OWNER_NAME || "ABDULLAH",
SEND_WELCOME: process.env.SEND_WELCOME || "true",
READ_MESSAGE: process.env.READ_MESSAGE || "true",
READ_CMD_ONLY: process.env.READ_CMD_ONLY || "true",
AUTO_REACT: process.env.AUTO_REACT || "false",
ANTI_BAD: process.env.ANTI_BAD || "true",
ANTI_CALL: process.env.ANTI_CALL || "true",
MODE: process.env.MODE || "public",
ANTI_LINK: process.env.ANTI_LINK || "true",
AUTO_VOICE: process.env.AUTO_VOICE || "true",
AUTO_STICKER: process.env.AUTO_STICKER || "false",
AUTO_REPLY: process.env.AUTO_REPLY || "true",
ALWAYS_ONLINE: process.env.ALWAYS_ONLINE || "true",
PUBLIC_MODE: process.env.PUBLIC_MODE || "true",
AUTO_TYPING: process.env.AUTO_TYPING || "true",
READ_CMD: process.env.READ_CMD || "false",
DEV: process.env.DEV || "923044975027",
ANTI_VV: process.env.ANTI_VV || "true",
ANTI_BOT: process.env.ANTI_BOT || "true",
ANTI_DELETE: process.env.ANTI_DELETE || "true",
ANTI_DELETE_TYPE: process.env.ANTI_DELETE_TYPE || "same",
AUTO_RECORDING: process.env.AUTO_RECORDING || "true",
AUTO_BLOCK: process.env.AUTO_BLOCK || "false",
GROQ_API_KEY: process.env.GROQ_API_KEY || "",
ANTI_EDIT: process.env.ANTI_EDIT || "false",
ANTI_SPAM: process.env.ANTI_SPAM || "false",
IMGBB_KEY: process.env.IMGBB_KEY || "",
ALIVE_IMG: process.env.ALIVE_IMG || "https://files.catbox.moe/yba2f9.jpg",
};
